### ISSUE TITLE
sorting by stars

### ISSUE THREAD

**Issue by lucasnaja** [GPortfolio/GPortfolio#119]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like a "sort by stars" option, it'd help a lot.

**Describe alternatives you've considered**
no one.

**Additional context**

My most starred repo is on the last position:
![Screenshot from 2019-09-20 15-30-05](https://user-images.githubusercontent.com/13838273/65350208-919f1500-dbbb-11e9-91d9-e3e8706b464b.png)

**Comment by Alexeykhr** [comment]
Thanks for the issue, I will implement this in 4.0.0 version

**Comment by Alexeykhr** [comment]
It came to realize even a little earlier than planned :)
