### ISSUE TITLE
possible to run two filters at once?

### ISSUE THREAD

**Issue by soneji** [GPortfolio/GPortfolio#250]
Hi
Is it possible to run two filters on the repositories at once. I mean I want to get rid of all the forks, apart from one, "flappy-musk"
```js
{ attr: 'fork', values: true, revert: true, more: '' },
{ attr: 'name', values: "flappy-musk", revert: true, more: '' },
```
But this does not seem to work. Once a filter has been applied are the repositories are completely removed from the repositories array?

I was thinking it might be possible to do something like:
```js
{ attr: 'fork', values: true, revert: true, more: '&& name!=\'flappy-musk\' ' },
```
but this does not seem to work

**Comment by Alexeykhr** [comment]
I am surprised that someone else finds this repository :)

Yes, it probably doesn’t work now, the code is here:
https://github.com/GPortfolio/GPortfolio/blob/master/core/modules/github/repositories.ts#L43
https://github.com/GPortfolio/GPortfolio/blob/master/core/classes/Filter.ts#L60

If I continue to add code, I will take note of this, thanks :)

**Comment by overclockedllama** [comment]
Ah no worries bro. It will be cool to see if you do implement it. Your project is so cool!

I've made a [fork](https://github.com/overclockedllama/GPortfolio) of your project btw, and added some cool features/new theme. Including [automatic repo updates](https://github.com/overclockedllama/GPortfolio/blob/master/.github/workflows/node.js.yml) with github actions! =D If you want to pull the changes upstream feel free to :)

You can check it out at https://soneji.xyz

**Comment by Alexeykhr** [comment]
Cool! I really liked the way you use Github Actions with cron schedule. I didn't know it was possible :)

**Comment by overclockedllama** [comment]
Hey, check this out => I added repository preview images and live demos! 
https://soneji.xyz 
https://github.com/overclockedllama/portfolio
